name: Discord PR Notification

on:
  pull_request:
    branches: [dev]
    types: [opened, reopened, ready_for_review]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_PR_WEBHOOK }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          BRANCH="${{ github.event.pull_request.head.ref }}"
          curl -H "Content-Type: application/json" -X POST -d "{
            \"content\": \"🚀 **Novo Pull Request aberto!**\n\n🔗 [${PR_TITLE}](${PR_URL})\n👤 Autor: ${AUTHOR}\n🌿 Branch: ${BRANCH}\"
          }" "$DISCORD_WEBHOOK"
